### ISSUE TITLE
TypeError: Cannot read property 'firstChild' of null

### ISSUE THREAD

**Issue by greyvugrin** [orteth01/react-scroll-lock-component#5]
Getting an error coming from line 37 of source:

`<div ref={r => this.scrollingElement = r.firstChild}>`

It seems like the ref is null.

Here is my implementation of it:

```
<ScrollLock>
       <div>
           <ul>
                { /* more stuff in here */ }
            </ul>
       </div>
</ScrollLock>
```

**Comment by greyvugrin** [comment]
Reverting changes in https://github.com/orteth01/react-scroll-lock-component/commit/c3664ce5236058ecefcfb2903cfa4a1a45d26fde fixed the problem for me.

**Comment by jchonde** [comment]
https://github.com/orteth01/react-scroll-lock-component/pull/4 fix this issue.

**Comment by orteth01** [comment]
Hey @greyvugrin! sorry for the delay! i've been away for the holidays.

@jchonde thanks for taking this on! reviewing #4 now!

**Comment by orteth01** [comment]
fixed by #4

**Comment by orteth01** [comment]
@greyvugrin please let me know if you are still getting the error

**Comment by greyvugrin** [comment]
Actually still seeing error, will test more tomorrow and post here

**Comment by orteth01** [comment]
@greyvugrin i've been trying to replicate your error with no luck. mind posting some more code?

**Comment by greyvugrin** [comment]
Actually the issue is that when I do `npm i react-scroll-lock-component` it installs 0.1.2, but I need 0.1.3 to get these changes. Will see why that is happening

**Comment by greyvugrin** [comment]
Seems like npm thinks 0.1.2 is the latest: https://www.npmjs.com/package/react-scroll-lock-component

**Comment by orteth01** [comment]
@greyvugrin can you try `npm i -S react-scroll-lock-component@0.1.3`?

if you run `npm view react-scroll-lock-component`, you'll see that version 0.1.3 is there. npm must just take a little time to update.

**Comment by greyvugrin** [comment]
Actually I'm not getting that.

When running the install command with 0.1.3 specified I get:
```
No compatible version found: react-scroll-lock-component@0.1.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.2, 0.1.1, 0.1.0, 0.0.3, 0.0.2, 0.0.1
```

And `npm view` yields

```
 name: 'react-scroll-lock-component',
  description: 'A React component wrapper that restricts scrolling capabilities of everything except for its children.',
  'dist-tags': { latest: '0.1.2' },
  versions: [ '0.0.1', '0.0.2', '0.0.3', '0.1.0', '0.1.1', '0.1.2' ],
```

**Comment by greyvugrin** [comment]
Using `npm i github:orteth01/react-scroll-lock-component -S` gives me 0.1.3

**Comment by orteth01** [comment]
very weird. here's my `npm view`

```
{ name: 'react-scroll-lock-component',
  versions: [ '0.0.1', '0.0.2', '0.0.3', '0.1.0', '0.1.1', '0.1.2', '0.1.3' ],
  'dist-tags': { latest: '0.1.3' },
  version: '0.1.3',
```

Googled around a little bit and some other people have had a similar issue. can you try again tomorrow? If it's still happening, i'll just bump to 0.1.4 and hopefully that will fix it.

**Comment by greyvugrin** [comment]
Haha yeah will try tomorrow and let you know, I have it pointing to Github for now anyway.

**Comment by orteth01** [comment]
@greyvugrin update on this?

**Comment by greyvugrin** [comment]
@orteth01 Hey thanks for the ping. Getting correct version on npm now. Thanks for all your help!
